spring.application.name=ecommerce

logging.level.root=INFO
logging.level.com.borneo.ecommerce=DEBUG
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=2003

app.jwtSecret=bF80myE0QiU/cp846ybXr4eyEDgEQbnh/YY+FZ7USlY=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# In application.properties
admin.secret.code=code123
vendor.secret.code=code123
app.upload.dir=/Users/MAC/Projects/borneo-react/public/images/
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dhaerieshan@gmail.com
spring.mail.password=yvxa yngs bvfm nllr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true